[package]
name = "text"
version = "0.0.1"
license = "MIT"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
description = "The package provides a text toolbox."
homepage = "https://github.com/hilbert-space/text"
repository = "https://github.com/hilbert-space/text"

[dependencies]
font = "*"
