[package]
name = "text"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/hilbert-space/text"
homepage = "https://github.com/hilbert-space/text"
description = "Text."
